// @ts-check
// Two independent sidebars:
//   * docsSidebar — hand-curated, hierarchical guidance content.
//   * apiSidebar  — fully auto-generated from the DocFX → Markdown output in docs/api.
//
// The API sidebar uses an `autogenerated` item so that every namespace/type page
// produced by the DocFxMarkdownGen bridge is picked up without editing this file.
// Ordering of generated categories is controlled by the `_category_.json` files
// that the markdown generator emits alongside the API pages.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // ---------------------------------------------------------------------------
  // Conceptual / guidance documentation (authored by hand).
  // ---------------------------------------------------------------------------
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      link: { type: 'generated-index', title: 'Getting Started', slug: '/getting-started' },
      items: ['getting-started/installation'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      link: { type: 'generated-index', title: 'Guides', slug: '/guides' },
      items: ['guides/authentication', 'guides/error-handling'],
    },
  ],

  // ---------------------------------------------------------------------------
  // C# API reference — generated. Do not edit by hand; regenerated each build.
  // The `dirName` is relative to the docs root (website/docs), so it points at
  // the Markdown that DocFX + DocFxMarkdownGen write into docs/api.
  // ---------------------------------------------------------------------------
  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      // The committed docs/api/index.md is the category landing page. It also
      // guarantees the sidebar is never empty (so the navbar "API Reference"
      // item always has a link target) before the generator has run.
      link: { type: 'doc', id: 'api/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
};

module.exports = sidebars;
